### ISSUE TITLE
images not saving

### ISSUE THREAD

**Issue by minxdragon** [Acconut/transloadit-demo#2]
Hi Account, thanks for this repo and clear instructions. 
When I implement this exactly as written it fails, I get a 500 error on reload because the images haven't saved to their directories. I can see them in the console and in transloadit so I know the assembly is firing, but when I go into the stack trace for the error on the python side I get 
`    for result in assembly['results']['thumbnail']:
      KeyError: 'thumbnail'`

it appears that the assembly no longer has the term 'thumbnail' maybe? when I edit out [thumbnail] I get more predictable errors, and printing the assembly results gets me this
`{'face_detect': [{'id': 'd3f744a449c6429c838ecc5b0f311d2a', 'name': 'test1.jpg', 'basename': 'test1', 'ext': 'jpg', 'size': 14075, 'mime': 'image/jpeg', 'type': 'image', 'field': 'file', 'md5hash': '119c57504f67a3dba659720cfd324d7f', 'original_id': '067f21fb48044d3583734773b52074f1', 'original_basename': 'test1', 'original_name': 'test1.jpg', 'original_path': '/', 'original_md5hash': 'ccb573a65e0233a07ee711dbf7e1c4ef', 'from_batch_import': False, 'is_tus_file': False, 'tus_upload_url': None, 'url': 'http://tmp-ap-southeast-1.transloadit.net/d3f744a449c6429c838ecc5b0f311d2a.jpg', 'ssl_url': 'https://tmp-ap-southeast-1.transloadit.net/d3f744a449c6429c838ecc5b0f311d2a.jpg', 'meta': {'width': 169, 'height': 228, 'date_file_modified': '2021/10/12 06:15:07 GMT', 'aspect_ratio': 0.741, 'has_clipping_path': False, 'frame_count': 1, 'colorspace': 'sRGB', 'has_transparency': False, 'average_color': '#b89184', 'orientation': 'Horizontal (normal)', 'svgViewBoxWidth': None, 'svgViewBoxHeight': None, 'date_recorded': None, 'date_file_created': None, 'title': None, 'description': None, 'duration': None, 'location': None, 'city': None, 'state': None, 'country': None, 'country_code': None, 'keywords': None, 'aperture': None, 'exposure_compensation': None, 'exposure_mode': None, 'exposure_time': None, 'flash': None, 'focal_length': None, 'f_number': None, 'iso': None, 'light_value': None, 'metering_mode': None, 'shutter_speed': None, 'white_balance': None, 'device_name': None, 'device_vendor': None, 'device_software': None, 'latitude': None, 'longitude': None, 'creator': None, 'author': None, 'copyright': None, 'copyright_notice': None, 'xp_title': None, 'xp_comment': None, 'xp_keywords': None, 'xp_subject': None, 'faces': [{'x1': 57, 'y1': 52, 'x2': 221, 'y2': 275, 'height': 228, 'width': 169, 'confidence': 99.99}], 'dominant_colors': None}, 'queue': 'live', 'queueTime': 0.02, 'execTime': 1.97, 'cost': 47960}]}`

I keep going around and around on this, without being able to get the files to save. could you please shed some light on what I should be looking for? I should say that I ensured that my links were all good and the directory locations, etc. I have stripped back the code to bare minimums and still I am running into drama.
thanks

**Comment by Acconut** [comment]
It seems as if you modified the Assembly instructions, so there is no longer a step named `thumbnail`. Did you try using `for result in assembly['results']['face_detect']` yet?

**Comment by minxdragon** [comment]
OMG. thank you! /facepalm. yes that was it. sorry I missed that!
